on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - "18"
          - "20"
          - "22"
          - "24"
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: npm test
        shell: bash
